"""Standalone async client for the Sigur OIF integration protocol.

This package implements "Протокол интеграции OIF" rev. 27.01.2025 (OIF 1.8,
Sigur 1.6.3.14) and deliberately contains no Home Assistant import, so that it
can be split out into its own library later without touching the protocol code.
"""

from __future__ import annotations

from .client import (
    BackoffController,
    ConnectionStats,
    Credentials,
    EventCallback,
    OifConnection,
    SubscribeMode,
    run_with_backoff,
)
from .commands import ALL_ACCESS_POINTS, ANONYMOUS, SigurApi
from .errors import (
    ERROR_TEXTS,
    OifErrorCode,
    SigurAuthError,
    SigurBusyError,
    SigurCommandError,
    SigurConnectionError,
    SigurError,
    SigurPermissionError,
    SigurProtocolError,
    SigurServerError,
    SigurTimeoutError,
    SigurTlsError,
    SigurUnknownAccessPointError,
    SigurUnknownObjectError,
    SigurUnsupportedVersionError,
)
from .event_codes import (
    EVENT_CODES,
    EventCategory,
    EventDefinition,
    ResolvedEvent,
    resolve_event_code,
)
from .parser import (
    AccessPointInfo,
    ApMode,
    ApOpenState,
    ApState,
    CredentialKey,
    Direction,
    DirectionCode,
    ObjectInfo,
    ObjectLocation,
    RawEvent,
    ZoneInfo,
)
from .transport import (
    DEFAULT_COMMAND_TIMEOUT,
    DEFAULT_CONNECT_TIMEOUT,
    DEFAULT_OIF_VERSION,
    DEFAULT_PORT,
    TLS_DISABLED,
    TLS_INSECURE,
    TLS_VERIFIED,
    OifTransport,
    TlsSettings,
    TransportSettings,
    create_ssl_context,
)

__all__ = [
    "ALL_ACCESS_POINTS",
    "ANONYMOUS",
    "DEFAULT_COMMAND_TIMEOUT",
    "DEFAULT_CONNECT_TIMEOUT",
    "DEFAULT_OIF_VERSION",
    "DEFAULT_PORT",
    "ERROR_TEXTS",
    "EVENT_CODES",
    "TLS_DISABLED",
    "TLS_INSECURE",
    "TLS_VERIFIED",
    "AccessPointInfo",
    "ApMode",
    "ApOpenState",
    "ApState",
    "BackoffController",
    "ConnectionStats",
    "CredentialKey",
    "Credentials",
    "Direction",
    "DirectionCode",
    "EventCallback",
    "EventCategory",
    "EventDefinition",
    "ObjectInfo",
    "ObjectLocation",
    "OifConnection",
    "OifErrorCode",
    "OifTransport",
    "RawEvent",
    "ResolvedEvent",
    "SigurApi",
    "SigurAuthError",
    "SigurBusyError",
    "SigurCommandError",
    "SigurConnectionError",
    "SigurError",
    "SigurPermissionError",
    "SigurProtocolError",
    "SigurServerError",
    "SigurTimeoutError",
    "SigurTlsError",
    "SigurUnknownAccessPointError",
    "SigurUnknownObjectError",
    "SigurUnsupportedVersionError",
    "SubscribeMode",
    "TlsSettings",
    "TransportSettings",
    "ZoneInfo",
    "create_ssl_context",
    "resolve_event_code",
    "run_with_backoff",
]
